### ISSUE TITLE
Document how to translate

### ISSUE THREAD

**Issue by Pablohn26** [farmOS-legacy/farmOS.org#18]
Hi, 

I would like to translate farmOS to Spanish. Having English and Spanish, farmOS would cover two of three most spoken languages in the World.

Could you document how to translate? If so, I would happy to translate all farmOS components.

**Comment by mstenta** [comment]
That's great @Pablohn26 !

Translations are something we're very excited to start building. Have you ever worked with translations in Drupal before? I haven't worked with Drupal translations myself, so I am not very familiar with the process. I just know that it is possible - but I can try to provide some guidance and overview into the process, and what we have already been thinking about for farmOS...

Currently, farmOS is built on Drupal 7, which has a set of third-party modules available that can be added in order to allow translations.  These are not included in the packaged farmOS release by default, but can be added and enabled by users fairly easily.  The website localize.drupal.org is where the translations themselves are contained, and those modules will pull them from there.  One of the modules lets you contribute translations back to localize.drupal.org.

I believe the two most important modules in Drupal 7 for this are:

https://www.drupal.org/project/l10n_update

https://www.drupal.org/project/l10n_client

Drupal.org provides a bunch of great documentation on how all this fits together in Drupal 7, so I would suggest starting here: https://www.drupal.org/docs/7/multilingual/translating-site-interfaces

And if you are able and willing to write up some simple instructions for other farmOS contributors based on your experience, that would be wonderful!

Now... with regard to the future... I am very eager to start working on the next version of farmOS, which will be built on Drupal 8.  Drupal 8 comes with the localization modules built into the core of Drupal itself, which means you don't need to download and install separate modules.  Translation and localization support was a major initiative in the development of Drupal 8, so it is much more mature and integrated. My thought has been that it will probably be easier to start an organized farmOS translation initiative once we are on Drupal 8.

But, that being said, that will take some time, and I really don't want to prevent non-English users from using farmOS in the meantime. So I absolutely would welcome your help in translating the current version of farmOS.  I think that most of the translations that are contributed to the current version will still be applicable in the next version, too, so it is worth doing - even if it is a bit more complicated right now.

There have been some others who have also expressed interest in providing translations.  It might be worth organizing everyone and writing up some documentation to help everyone get started.  Here are two related discussions that have taken place in the farmOS issue queue on drupal.org:

https://www.drupal.org/node/2690051

https://www.drupal.org/node/2772031

**Comment by mstenta** [comment]
<strike>The other key piece of information I should add: farmOS is not just one project, but a collection of various modules. So when you are looking at https://localize.drupal.org, and you see the "pick a project" search box in the upper right, it's important to be aware that each module and project will need it's own set of translations.

For example, here is the "farmOS" installation profile project: https://localize.drupal.org/translate/projects/farm

And here is the "Farm Crop" module: https://localize.drupal.org/translate/projects/farm_crop

And "Farm Livestock": https://localize.drupal.org/translate/projects/farm_livestock

The full list of projects that comprise farmOS are documented on farmOS.org: http://farmos.org/development/projects

In Drupal 8, we may merge a lot of these together into the one core farmOS installation profile project, to make management easier.  But there will always be the ability to have third-party contributed farmOS modules, so there will always be multiple projects that need translation, not just one.

This shouldn't make it any more difficult to contribute translations, though - because each module is relatively small and will only have a subset of the strings that need to be translated. It's just something to be aware of.</strike>

<strong>Edit: this is no longer true. Most farmOS modules were merged into the distribution.</strong>

**Comment by Arcadiapps** [comment]
@Pablohn26 

Hola Pablo (sorry for this comment in spanish mstenta, just trying to join forces with Pablo in this subject) 

¿Has podido avanzar en esto? Yo también lo quiero traducir al castellano y al euskera quizás podemos unir esfuerzos, ¿que te parece?

Un saludo

**Comment by mstenta** [comment]
:+1:

**Comment by Pablohn26** [comment]
@Arcadiapps I did few translations just as a test but I have not found time to continue with it, so you can carry on with this issue without problem. We keep in touch.

**Comment by Arcadiapps** [comment]
@Pablohn26 Ok I´m not familiar with the process of translating in Drupal, as you managed to translate, could you give me something like an easy roadmap to follow your steps?

Thanks in advance :-)

**Comment by Pablohn26** [comment]
It is my first time also with Drupal :) All the information that I know is in this issue.
As a summary, you have to enter to module translation (for example [this](https://localize.drupal.org/translate/projects/farm_crop), the remaining modules are above) , create an account if you do not have it, select your language and add translation suggestions. Then click below on "Save changes". 

To be honest, I do not know how set the suggestion as translation, I guess only @mstenta have permission to do that. 

@Arcadiapps if this information is not enough, feel free to send me an email :)

**Comment by edwardbaekelandt** [comment]
@Pablohn26 For each language/translation-group on localize.drupal.org there are moderators who can approve suggestions. These moderators are experienced translators and trusted members in their translation group.
So like you said you can add translation suggestions on localize.drupal.org for the languages you want, but then you'll have to wait a few days until they are approved.

As @mstenta said, because the drupal 7 version of farmOS is splitted in multiple modules, it will be a little bit more work to be sure that all strings are translated. But this is not a blocking obstacle.

To clarify this a little bit further, I've added some of the official documentation below:

> **How to contribute?**
> - If not already a member of the translation team, go to the Overview screen for your language and join with the big green Join button.
> - Look at the team's Board page for information on terminology, review process, etc. if available.
> - Find untranslated strings with the language link on this page (in Drupal 8), or adjust the filters for other projects.
> - Submit suggestions for untranslated strings.

You can find more information [here](https://www.drupal.org/contribute/translations) and [here](https://www.drupal.org/node/302194)

@Arcadiapps I hope this gives you enough information to start contributing translations to localize.drupal.org if you still have any questions, feel free to contact me.

**Comment by mstenta** [comment]
Thank you @edwardbaekelandt for the detailed insights!

**Comment by calbasi** [comment]
@Pablohn26 @Arcadiapps Yo tengo experiencia en traducciones con Drupal. No he probado aún FarmOS, pero me interesa. Si os puedo ayudar, ya me diréis ;-)

**Comment by Pablohn26** [comment]
@mstenta could you [update](https://github.com/farmOS/farmOS.org/blob/7.x-1.x/docs/community/contribute.md) how to translate FarmOS ?

**Comment by mstenta** [comment]
@Pablohn26 if you or @calbasi are interested in writing some instructions on that page in a pull request, I can merge it in! I don't have enough experience with enabling translations in Drupal to explain it myself, but it sounds like you do?

Or if you can just draft some text here in these comments, I can add it to the farmOS.org page myself. Either way! Thanks for helping to get this off the ground! :-)

**Comment by calbasi** [comment]
If there is anyone interested in localize his FarmOS site to any other language I can do it and then I can document the steps.

**Comment by mstenta** [comment]
Thanks @calbasi!

Now that I think of it: we probably need to document two things on farmOS.org...

1. How to enable localization modules in farmOS and pull in the contributed translations.
2. How to contribute translations to localize.drupal.org

1 probably belongs in the hosting farmOS section. 2 belongs in the contributing to farmOS section.

**Comment by calbasi** [comment]
I also think so

**Comment by calbasi** [comment]
Ok, what do you think about this:

Localization to another language

1. Enable Locale module

2. Add your language at /admin/config/regional/language
2.1 Set this new language as default language, if desired.
2.2 Set the Detection and Selection options at /admin/config/regional/language/configure

3. Download and enable Localization_update module (https://www.drupal.org/project/l10n_update), For example, using drush:
> drush en l10n_update

3.1 Configure it at /admin/config/regional/language/update
Suggested: 

> Check for updates: weekly
> Import behaviour: Only overwrite imported translations, customized translations are kept.

4. If you are in a hurry, first time, go to /admin/config/regional/translate/update and check manually for tranlations and update them.

5. If there are some strings not translated, you can do it at http://farmos.bufala.cat/en/admin/config/regional/translate/translate and, if possible, add them to https://localize.drupal.org. You could use this additional module to do both tasks together: https://www.drupal.org/project/l10n_client

**Comment by mstenta** [comment]
@calbasi That worked for me! Thanks! The only part I didn't try was step 5.

I was also able to replicate the issue you reported here: https://www.drupal.org/project/farm/issues/3066193 - I will comment on that with my findings.

Do you want to want to make a pull request to add this to farmOS.org? Otherwise I can do it when I have some time.

**Comment by calbasi** [comment]
I can do it if you agree this content... I'm sure my English could be
improved :-p
El dj 04 de 07 de 2019 a les 04:39 -0700, en/na Pablo Hinojosa va
escriure:

**Comment by mstenta** [comment]
@calbasi Please do! It looks great to me!

**Comment by mstenta** [comment]
> Check for updates: weekly
Import behaviour: Only overwrite imported translations, customized translations are kept.

Side thought: eventually we may want to enable these modules by default and include this configuration automatically in farmOS. This would simplify the process of getting set up.

**Comment by calbasi** [comment]
Here you are, the pull request: https://github.com/farmOS/farmOS.org/pull/57

**Comment by mstenta** [comment]
Merged and deployed #57 - thanks @calbasi!

For anyone else finding this thread, please refer to: https://farmOS.org/hosting/localization/

If we want to expand on that, let's open a new issue.

**Comment by calbasi** [comment]
Your welcome, @mstenta !
