### ISSUE TITLE
Using Bookdown to compile a FarmOS manual 

### ISSUE THREAD

**Issue by MorgsBrew** [farmOS-legacy/farmOS.org#51]
# Question or Suggestion

## Following on the monthly call (13/3/29).

We spoke about finding ways to encourage or open community participation in the continued development of FarmOS. One of the suggestions was to have places to point people for contributing and learning. In my time learning R I used a number of different books written in RMarkdown using Bookdown to help me manipulate my own coding. I think that there is a lot of content on the current website that would fit nicely into a  #bookdown format. I have attached links to a few examples if you are not familiar with the format. 

https://happygitwithr.com/
https://bookdown.org/yihui/bookdown/
https://bookdown.org/yihui/rmarkdown/
https://bookdown.org/

PS, I can't find the **tags** function or know the markdown to make it *pretty*

**Comment by mstenta** [comment]
Closing this as "outdated" since a lot of things are changing now ahead of farmOS v2's release! We have a new repo that will be the home for farmOS.org moving forward: https://github.com/farmOS/farmos.org-EXPERIMENTAL, and farmOS v2 user guides will be included in the farmOS repo itself. Still curious to see if this would be worth exploring, though, @MorgsBrew - maybe we can reasses once the dust settles on v2 and open a new issue in the appropriate place...
